#!/bin/bash
cd /home/$USER/UAV-Projects/visual_navigation
source /opt/ros/noetic/setup.bash
source devel/setup.bash
source /home/$USER/PX4-Autopilot/Tools/setup_gazebo.bash /home/$USER/PX4-Autopilot /home/$USER/PX4-Autopilot/build/px4_sitl_default > /dev/null
export ROS_PACKAGE_PATH=/home/$USER/PX4-Autopilot:/home/$USER/PX4-Autopilot/Tools/sitl_gazebo:$ROS_PACKAGE_PATH
roslaunch px4 visual_navigation_test.launch &
sleep 5
rosrun visual_navigation_node visual_navigation_executable
wait 